// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import "dart:core";
import 'package:flutterscript/reflector.dart' as prefix0;

// ignore:unused_import
import "package:reflectable/mirrors.dart" as m;
// ignore:unused_import
import "package:reflectable/src/reflectable_builder_based.dart" as r;
// ignore:unused_import
import "package:reflectable/reflectable.dart" as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Reflector(): new r.ReflectorData(
      <m.TypeMirror>[
        new r.NonGenericClassMirrorImpl(
            r"App",
            r"flutterscript.reflector.App",
            7,
            0,
            const prefix0.Reflector(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r"": (b) => ({title, theme}) =>
                  b ? new prefix0.App(title: title, theme: theme) : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r"==": 0,
              r"toString": 3,
              r"noSuchMethod": 0,
              r"hashCode": 3,
              r"runtimeType": 3,
              r"identityMethod": 0,
              r"withOptionalPositionalParameters": 1,
              r"withOptionalNamedParameters": 2,
              r"title": 3,
              r"title=": 0,
              r"theme": 3,
              r"theme=": 0
            })
      ],
      null,
      null,
      <Type>[prefix0.App],
      1,
      {
        r"==": (dynamic instance) => (x) => instance == x,
        r"toString": (dynamic instance) => instance.toString,
        r"noSuchMethod": (dynamic instance) => instance.noSuchMethod,
        r"hashCode": (dynamic instance) => instance.hashCode,
        r"runtimeType": (dynamic instance) => instance.runtimeType,
        r"identityMethod": (dynamic instance) => instance.identityMethod,
        r"withOptionalPositionalParameters": (dynamic instance) =>
            instance.withOptionalPositionalParameters,
        r"withOptionalNamedParameters": (dynamic instance) =>
            instance.withOptionalNamedParameters,
        r"title": (dynamic instance) => instance.title,
        r"theme": (dynamic instance) => instance.theme
      },
      {
        r"title=": (dynamic instance, value) => instance.title = value,
        r"theme=": (dynamic instance, value) => instance.theme = value
      },
      null,
      [
        const [1, 0, null],
        const [2, 1, null],
        const [
          1,
          0,
          const [#two]
        ],
        const [0, 0, null],
        const [
          0,
          0,
          const [#title, #theme]
        ]
      ])
};

final _memberSymbolMap = null;

initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
